### ISSUE TITLE
run_docker.py failing when using proxy config

### ISSUE THREAD

**Issue by jackstuart92** [dynatrace-oss/dynatrace-gcp-function#53] opened 2021-03-05 16:46 UTC
Hey @Dawid-Kaszubski, Thanks for getting this in so quickly. I'm running into some issues running the code with the proxy settings enabled.

The environment variables exist

```
HTTPS_PROXY="http://<REDACTED>"
USE_PROXY="DT_ONLY"
```

However the run_docker.py script fails in due to an exception raised in the fast_check lib.
```
2021-03-05 09:26:57.480281 : Unable to get Dynatrace token metadata. Error details:
```
exception block:
```
async def get_dynatrace_token_metadata(dt_session: ClientSession, context: LoggingContext, dynatrace_url: str, dynatrace_api_key: str, timeout: Optional[int] = 2) -> dict:
    try:
        response = await dt_session.post(
            url=f"{dynatrace_url.rstrip('/')}/api/v1/tokens/lookup",
            headers={
                "Authorization": f"Api-Token {dynatrace_api_key}",
                "Content-Type": "application/json; charset=utf-8"
            },
            json={
                "token": dynatrace_api_key
            },
            timeout=timeout)
        if response.status != 200:
            context.log(f'Unable to get Dynatrace token metadata: {response.status}, url: {response.url}, reason: {response.reason}')
            return {}

        return await response.json()
    except Exception as e:
        context.log(f'Unable to get Dynatrace token metadata. Error details: {e}')
        return {}
```
If i execute the local_test.py script the gcp function respects the environment variables and is able to connect to both the Dynatrace tenant and google apis successfully. Do you have any suggestions to help me debug this futher?

Many thanks
Jack

**Comment by jackstuart92** [comment] 2021-03-08 16:16
update: I set TRUST_ENV_PROXY = "true" in the config map. No change in behaviour

**Comment by jackstuart92** [comment] 2021-03-09 10:06
Hey Dawid,

I tried originally without the TRUST_ENV_PROXY setting configured. Currently the USE_PROXY and HTTPS_PROXY environment variables are set however the run_docker.py script is failing as it is unable to reach the dynatrace tenant. If I run local_test.py the script completes successfully reaching both the Dynatrace tenant via the proxy and the google apis without the proxy.

Cheers
JAck

**Comment by Dawid-Kaszubski** [comment] 2021-03-09 12:39
`TRUST_ENV_PROXY ` set as true is not needed - `USE_PROXY` sets it for a specific client.

The problem occurs only for docker because the function version doesn't execute this request.

I've tried to reproduce your problem and I was able to get the same log when I set a delay for my proxy. This request has a very strict timeout - 2s. 
In my case aiohttp.ClientSession.post() had thrown TimeoutError, which has no message. Because of that, there were no `Error details` in the log. I assume you have access to the code and can edit it, so please try to set the timeout argument to a higher value (maybe 30-60) in get_dynatrace_token_metadata method. If you confirm my hypothesis and it starts working, we will add a fix to the repo. 


BTW I dunno what happened to the previous comment, it was accidentally truncated.

**Comment by Dawid-Kaszubski** [comment] 2021-03-15 09:41
It still looks like TimeoutError. Is it possible, that something blocks requests to proxy? Maybe your firewall (if exists) blocks requests from docker container. 
Also, can you give me more details about your setup? Python version, environment variables set.

**Comment by Dawid-Kaszubski** [comment] 2021-03-23 08:39
Hey @jackstuart92 , any updates?

**Comment by Dawid-Kaszubski** [comment] 2021-03-31 08:10
Closing due to missing input from issue author. Please contact us if the issue is still relevant.

**Closed by Dawid-Kaszubski** 2021-03-31 08:10 UTC
